package com.example.labxspringboot.entity.enume;

public enum TypeAnalyse {

    HEMATOLOGIE,
    CHIMIE_CLINIQUE,
    IMMUNOLOGIE,
    MICROBIOLOGIE,
    BIOLOGIE_MOLECULAIRE_ET_GENETIQUE,
    ENDOCRINOLOGIE,
    COAGULATION,
    RADIOLOGIE_ET_IMAGERIE,
    PATHOLOGIE,
    TOXICOLOGIE
}
